version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: election2_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: election_db2
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./election_com_dep (2).sql:/docker-entrypoint-initdb.d/init.sql

  adminer:
    image: adminer
    container_name: election_adminer2
    restart: always
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres
      ADMINER_DESIGN: pepa-linha

volumes:
  postgres_data:
